version: "3.7"

services:
  pgdb:
    build: env/postgres
    image: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=<your_pg_password>

  client:
    depends_on:
      - pgdb
    build: env/client
    image: client
    volumes:
      - $PWD/tmp:/mount
